version: '3.8'
services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql  # 持久化 MySQL 数据

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  # 映射端口以便本地访问
    volumes:
      - mongo-data:/data/db  # 持久化 MongoDB 数据

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: crossskill
volumes:
  mysql-data:
  mongo-data: